name: Auto Label PRs and Issues

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Auto Label
      uses: actions/labeler@v4
      with:
        configuration-path: .github/labeler.yml
