name: "Build test"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
  
    - name: Create Venv
      run: |
        python -m venv .venv
        
    - name: "Install dependencies"
      run: |
        .venv/bin/pip install --upgrade pip
        .venv/bin/pip install -r ./scripts/requirements.txt
        
    - name: "Build the source"
      run: |
        sudo ./scripts/run.sh
